version: '3.9'

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx_cont
    ports:
      - "80:80"
    restart: always
    depends_on:
      django_app:
        condition: service_healthy
    networks:
      - notes-app-nw

  django_app:
    build:
      context: .
    image: django_app
    container_name: django_cont
    ports:
      - "8000:8000"

    command: sh -c "sleep 15 && python manage.py migrate --noinput && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"

    env_file:
      - .env

    depends_on:
      mysql:
        condition: service_healthy

    restart: always

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/admin || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

    networks:
      - notes-app-nw

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: django
      MYSQL_PASSWORD: django123

    volumes:
      - my_sql_data:/var/lib/mysql

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

    networks:
      - notes-app-nw

volumes:
  my_sql_data:

networks:
  notes-app-nw:
